name: shebang-remote-dev

services:
  app:
    image: shebang-remote-app-dev:latest
    hostname: "app"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        br.com.shebang-remote.project: "Shebang Remote"
        br.com.shebang-remote.service: "app"
    depends_on:
      - postgresql
    volumes:
      - ${PWD}:/usr/src/app
    networks:
      - net-bridge
    ports:
      - "8000:8000"
    env_file:
      - ${PWD}/src/server/.env_dev

  postgresql:
    image: shebang-remote-postgresql-dev:latest
    hostname: "postgresql"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        br.com.shebang-remote.project: "Shebang Remote"
        br.com.shebang-remote.service: "postgresql"
    volumes:
      - postgresql-db:/var/lib/postgresql/data
    networks:
      - net-bridge
    ports:
      - "6432:5432"
    env_file:
      - ${PWD}/src/server/.env_dev

volumes:
  postgresql-db:

networks:
  net-bridge:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "192.168.18.76"
